
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",
        USER_ADD_NEW: "USER_ADD_NEW",
        ROLE_ADD_NEW: "ROLE_ADD_NEW",
        GROUP_ADD_NEW: "GROUP_ADD_NEW",
        POST_ADD_NEW: "POST_ADD_NEW",
        POST_HISTORY: "POST_HISTORY",
        EDU_ADD_NEW: "EDU_ADD_NEW",
        EDU_PLAN_ADD_NEW: "EDU_PLAN_ADD_NEW",
        CHECK_CHILDREN_MODAL: "CHECK_CHILDREN_MODAL",
        ADD_ATTENDANCE_MODAL: "ADD_ATTENDANCE_MODAL",
        ADD_ATTENDANCE_DETAIL_MODAL: "ADD_ATTENDANCE_DETAIL_MODAL",
        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
    },
});
